### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by andriodious** [Pyhive/Pyhiveapi#18]
Examples in readme.md do not represent current sources

**Comment by KJonline** [comment]
@andriodious what do you mean by current sources?

**Comment by andriodious** [comment]
> @andriodious what do you mean by current sources?

I may be doing something wrong but this is what I tried:

git clone https://github.com/Pyhive/Pyhiveapi.git
.
.
.
from pyhiveapi import Hive, SMS_REQUIRED

session = Hive(username="HiveUserName", password="HivePassword")
login = session.login()

if login.get("ChallengeName") == SMS_REQUIRED:
    code = input("Enter 2FA code: ")
    session.sms_2fa(code, login)

session.startSession()
.
.
.
Python 3.6.0 (default, Oct  6 2020, 09:51:31) 
[GCC 4.9.3] on linux
Type "copyright", "credits" or "license()" for more information.
Traceback (most recent call last):
  File "/home/pi/LightSwitch/newer_hive/HiveTest.py", line 6, in <module>
    if login.get("ChallengeName") == SMS_REQUIRED:
AttributeError: 'coroutine' object has no attribute 'get'

**Comment by KJonline** [comment]
Its because you have cloned the repo and installed it via the setup file I would recommend installing the latest version via pip.

The library is written in Async and there is a build job to convert it to sync you have bypassed that and gone straight to install.

I would run ```pip install pyhiveapi ```

**Comment by andriodious** [comment]
Much appreciated, I am getting further now.

pip installed

Enter 2FA code: ******
Traceback (most recent call last):
  File "/home/pi/LightSwitch/newer_hive/HiveTest.py", line 8, in <module>
    session.sms_2fa(code, login)
AttributeError: 'Hive' object has no attribute 'sms_2fa'

**Comment by KJonline** [comment]
HiveReauthRequired is triggered when no data is unable to get data back from the api.

**Comment by andriodious** [comment]
If I switch to an account with no 2FA enabled, the error does not occur and I can interact with the session as expected and view devices and data.

When I switch back to an account with 2FA enabled, the HiveReauthRequired is triggered.

The 2FA code comes across on my mobile device as expected.

**Comment by andriodious** [comment]
I can confirm all is working fine with main Hive user account.

Please note that other accounts created under the main account == no data back from API

**Comment by martintoreilly** [comment]
Hi @andriodious and @KJonline. Sorry to wake a closed issue, but some of us are experiencing this same problem when trying to use accounts with Family/Partner access in Home Assistant (see [this issue](https://github.com/home-assistant/core/issues/51085)). I'd like to try and find a solution to this and am happy to help with digging into this. See below for my investigation so far.

The below is using a new account given "Partner" access to my Hive home (I originally only granted more restricted "Family" permissions to my home to the new account but these did not seem to let me see the devices even when my home was selected in the Hive android app).

- When logged into the Hive website with the Partner account, no devices are shown, with all logins redirected to the "install" page
- When logged into the Hive android app with the Partner account, there are no devices under the primary "Home", but my home appears as a **second** home selectable right at the top of the main menu. When selected, all the devices in my home are accessible.

I think the issue of no devices being returned from the API call may be due to these Family/Partner accounts being full-fledged Hive accounts with their own primary Hive home, with the "Partner/Family" access to another home being via some kind of secondary home access path.

Given that the secondary home can be accessed from the Hive android app, I think there must be some API functionality that allows a secondary Hive home to be selected. I'm happy to do some digging into the API, but I've tried to find documentation on the hive API online but have not been successful. Would you be able to point me to some documentation for it?

**Comment by KJonline** [comment]
Hi @martintoreilly unfortunately there is no hive api documentation. This library has been built by proxing a mobile devices and intercepting the requests that hive send to there server.

to be able to support family access you would need to provide api calls and responses using the above method omitting any sensitive data. As I don’t have family access to another home I cannot do this.

**Comment by martintoreilly** [comment]
Hi @KJonline. I've done some experimenting with the Hive API and have stumbled across a `homeId` query parameter that looks like it allows selection of a secondary Hive Home for users with guest permissions. 

So far I've verified this works for the `https://beekeeper.hivehome.com/1.0/nodes/all`, `https://beekeeper.hivehome.com/1.0/devices` and `https://beekeeper.hivehome.com/1.0/products` endpoints for a user with "Partner" access to my Hive Home and no devices/products in their primary Hive Home. It does not appear to work for the `https://beekeeper.hivehome.com/1.0/actions` endpoint - I can see two actions when using my Owner account and none using my Partner account, whether or not I add the `homeId` parameter.

The structure of the responses from all the endpoints are the same when called with and without the `homeId` parameter, but the responses with my products in them are very long with lots of IDs and schedule data to redact. I think you already parse all these endpoints in the library, so if you can get by without the responses that would be great. If redacted full responses would still be helpful, let me know and I'll provide them. I've summarised the differences for the `https://beekeeper.hivehome.com/1.0/nodes/all` endpoint below.

- Without the `homeId` parameter (`https://beekeeper.hivehome.com/1.0/nodes/all`), the response only contains details of the user and the homes they have access to.

- With the secondary home specified in the `homeId` parameter (`https://beekeeper.hivehome.com/1.0/nodes/all?homeId=<hom-id-guid>`), the response additionally contains all the product and device details I see when making the query with a token from my owner account for that home without the `homeId` specified.

The response from a call to `https://beekeeper.hivehome.com/1.0/nodes/all` appears to be essentially the same as the response from a call to `https://beekeeper.hivehome.com/1.0/global/admin-login`, so it might be possible to pick up the list of homes an account has access to as part of log-in. I see you use the `https://beekeeper.hivehome.com/1.0/cognito/login` endpoint in the library, but I wasn't able to authenticate to this (I've been reusing the `token` I got from snooping my log in to the Hive website for these experiments).

**Comment by martintoreilly** [comment]
Looking more at the missing actions, both actions appear in Hive android app when logged in as the Partner account. They also both appear in the response from `https://beekeeper.hivehome.com/1.0/nodes/all` when called with the Partner account and using my `homeId`. However, they don't appear when adding the `homeId` parameter to the call to `https://beekeeper.hivehome.com/1.0/actions`.
